version: "3.8"
services:
  db:
    image: "postgres"
    environment: 
      POSTGRES_PASSWORD: example
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./demo:/tmp/demo